In [2]:
import pandas as pd
df = pd.read_csv("name_height_outlier.csv")
df

              Name  Height_cm
0     Aarav Sharma        172
1      Priya Patel        160
2      Rohan Mehta        178
3     Ananya Singh        165
4       Vikram Rao        181
5       Neha Gupta        158
6       Arjun Nair        175
7       Sneha Iyer        162
8      Karan Verma        169
9       Isha Desai        157
10    Rahul Kapoor        174
11     Meera Joshi        163
12    Dev Malhotra        400
13  Pooja Kulkarni        159
14      Aditya Sen        176

In [3]:
max_threshold = df["Height_cm"].quantile(0.95) #finds the 95th percentile value.
max_threshold

np.float64(246.69999999999976)

In [4]:
df[df['Height_cm']>max_threshold]

            Name  Height_cm
12  Dev Malhotra        400

In [5]:
min_threshold = df["Height_cm"].quantile(0.05) #finds the 5th percentile value.
min_threshold

np.float64(157.7)

In [6]:
df[df['Height_cm']<min_threshold]

         Name  Height_cm
9  Isha Desai        157

In [7]:
df[(df["Height_cm"]<max_threshold) & (df["Height_cm"]>min_threshold)]

              Name  Height_cm
0     Aarav Sharma        172
1      Priya Patel        160
2      Rohan Mehta        178
3     Ananya Singh        165
4       Vikram Rao        181
5       Neha Gupta        158
6       Arjun Nair        175
7       Sneha Iyer        162
8      Karan Verma        169
10    Rahul Kapoor        174
11     Meera Joshi        163
13  Pooja Kulkarni        159
14      Aditya Sen        176

# Lets do it on Complex Data

In [8]:
df = pd.read_csv("Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [9]:
df.shape

(545, 13)

In [10]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [11]:
df["price_per_sqft"] = df["price"] / df["area"]
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,736.312500
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,601.374570
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455

In [12]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking,price_per_sqft
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578,993.326978
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586,346.537025
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000,270.395550
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000,745.370370
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000,952.380952
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000,1184.615385
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000,2640.000000

In [13]:
min_threshold, max_threshold = df.price_per_sqft.quantile([0.001,0.999])
min_threshold, max_threshold

(296.391279919092, 2443.1890813648356)

In [14]:
df[df.price_per_sqft < min_threshold]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
403,3500000,12944,3,1,1,yes,no,no,no,no,0,no,unfurnished,270.39555

In [15]:
df[df.price_per_sqft > max_threshold]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished,2640.0

In [16]:
df2 = df[(df.price_per_sqft > min_threshold) & (df.price_per_sqft < max_threshold)]
df2

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_sqft
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,736.312500
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,601.374570
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455

In [17]:
df2.shape

(543, 14)